# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PIL import Image


questionimage= Image.open("C:/Users/Hossms/Downloads/Question.png")
questionimage=questionimage.resize((300,300))
questionimage.save("C:/Users/Hossms/Downloads/Question.png")

class Ui_testWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 720)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 301, 361))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Hossms/Downloads/Question.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 70, 301, 361))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Hossms/Downloads/Question.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 70, 301, 361))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/Hossms/Downloads/Question.png"))
        self.label_3.setObjectName("label_3")
        self.Fathertext = QtWidgets.QLabel(self.centralwidget)
        self.Fathertext.setGeometry(QtCore.QRect(70, 30, 161, 21))
        self.Fathertext.setAlignment(QtCore.Qt.AlignCenter)
        self.Fathertext.setObjectName("Fathertext")
        self.Sontext = QtWidgets.QLabel(self.centralwidget)
        self.Sontext.setGeometry(QtCore.QRect(420, 40, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Sontext.setFont(font)
        self.Sontext.setAlignment(QtCore.Qt.AlignCenter)
        self.Sontext.setObjectName("Sontext")
        self.Mothertext = QtWidgets.QLabel(self.centralwidget)
        self.Mothertext.setGeometry(QtCore.QRect(760, 40, 161, 16))
        self.Mothertext.setAlignment(QtCore.Qt.AlignCenter)
        self.Mothertext.setObjectName("Mothertext")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 450, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.selectFile)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 500, 251, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.genetation_father)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 510, 251, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.genetation_mother)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 600, 161, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parent Detector"))
        self.Fathertext.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Father</span></p></body></html>"))
        self.Sontext.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Son</span></p></body></html>"))
        self.Mothertext.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Mother </span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.pushButton_2.setText(_translate("MainWindow", "Generate Father Picture"))
        self.pushButton_3.setText(_translate("MainWindow", "Generate Mother Picture"))
        self.pushButton_4.setText(_translate("MainWindow", "Back"))

      
    def genetation_father(self):
        image= Image.open("E:/Samster/Graduation/cnnmodelparentfacedetector/parent face generator/datasets/parent/test/fd_001_1.jpg")
        image=image.resize((301,361))
        image.save("E:/Samster/Graduation/cnnmodelparentfacedetector/parent face generator/datasets/parent/test/fd_001_1.jpg")
        self.label.setPixmap(QtGui.QPixmap("E:/Samster/Graduation/cnnmodelparentfacedetector/parent face generator/datasets/parent/test/fd_001_1.jpg"))
        
    def genetation_mother(self): 
        image= Image.open("E:/Samster/Graduation/cnnmodelparentfacedetector/parent face generator/datasets/parent/test/pc_0692_1.jpg")
        image=image.resize((301,361))
        image.save("E:/Samster/Graduation/cnnmodelparentfacedetector/parent face generator/datasets/parent/test/pc_0692_1.jpg")
        self.label_3.setPixmap(QtGui.QPixmap("E:/Samster/Graduation/cnnmodelparentfacedetector/parent face generator/datasets/parent/test/pc_0692_1.jpg"))
    
    
    
    def selectFile(self): 
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Hossms/Downloads/Question.png"))
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/Hossms/Downloads/Question.png"))
        fname = QFileDialog.getOpenFileName(None, 'Open file', 'D:')
        print(fname[0])
        image= Image.open(fname[0])
        image=image.resize((301,361))
        image.save(fname[0])
        self.label_2.setPixmap(QtGui.QPixmap(fname[0]))
    

if __name__ == "__main__":
    
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_testWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
